debezium:
  connector:
    name: my-connector
    connector.class: io.debezium.connector.mysql.MySqlConnector
    tasks.max: 1
    database.hostname: localhost
    database.port: 3306
    database.user: root
    database.password: root
    database.server.id: 184054
    database.server.name: my-server
    database.history.kafka.bootstrap.servers: localhost:9092
    database.history.kafka.topic: dbhistory.my-server